
export const SET_DOGS = "SET_DOGS";
export const SET_TEMPERAMENTS = "SET_TEMPERAMENTS";
export const SET_DOG_DETAIL = "SET_DOG_DETAIL";
export const SORT_DOGS = "SORT_DOGS";
export const NEXT_PAGE = "NEXT_PAGE";
export const PREV_PAGE = "PREV_PAGE";
export const FILTER_DOGS_TEMPERAMENT = "FILTER_DOGS_TEMPERAMENT";
export const FILTER_DOGS_ORIGIN = "FILTER_DOGS_ORIGIN";
